### ISSUE TITLE
Unable to patch Acrobat DC

### ISSUE THREAD

**Issue by elvergal** [E-Soda/CCStopper#5]
The acrobatfix script is not working for me.... Acrobat DC is still asking to log in

Error displayed: 
```
ERROR: El sistema no ha podido encontrar la clave o el valor del Registro
especificados.
The target registry key cannot be found, or it has been edited already. Cannot proceed with Acrobat fix.
```

Regards

**Comment by E-Soda** [comment]
Could you send a screenshot of what you see when you go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Adobe\Adobe Acrobat\DC\Activation` in the registry?

If you see _IsAMTEnforced_ instead of _IsNGLEnforced_ as the registry key, then it has been patched already, and that you need to just apply [homescreenfix](https://www.reddit.com/r/GenP/wiki/faq#wiki_homescreenfix).

DC needs to be patched first, then the registry fix can be applied.

**Comment by elvergal** [comment]
> 
> 
> Could you send a screenshot of what you see when you go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Adobe\Adobe Acrobat\DC\Activation` in the registry?
> 
> If you see _IsAMTEnforced_ instead of _IsNGLEnforced_ as the registry key, then the registry has been edited/patched already, and that you need to just apply [homescreenfix](https://www.reddit.com/r/GenP/wiki/faq#wiki_homescreenfix).
> 
> DC needs to be cured/patched first (w/genp), then the registry fix can be applied.

None of the above options seems to be available

![imagen](https://user-images.githubusercontent.com/63084403/121141164-4a7a0d00-c800-11eb-8b60-a6c2ead6f808.png)

**Comment by E-Soda** [comment]
Looks like there is no registry value, you can create a DWORD value called `IsAMTEnforced` with a value of 1, and it should work. You don't need to run fix acrobat with the script after this.

**Comment by chunk2k20** [comment]
ive somehow not even got adobe as an option?
![image](https://user-images.githubusercontent.com/111137872/184388030-d9f01985-aefe-4745-9efc-cd8ff7e3598b.png)
